[all:vars]
ansible_user=ubuntu
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[load_balancer]
lb-01 ansible_host=192.168.1.10

[web_servers]
web-01 ansible_host=192.168.1.11
web-02 ansible_host=192.168.1.12

[app_servers]
app-01 ansible_host=192.168.1.21
app-02 ansible_host=192.168.1.22

[db_servers]
db-master ansible_host=192.168.1.31 role=master
db-slave ansible_host=192.168.1.32 role=slave

[db_master]
db-master ansible_host=192.168.1.31

[db_slave]
db-slave ansible_host=192.168.1.32
